### ISSUE TITLE
Exposing ui_state?

### ISSUE THREAD

**Issue by cristeigabriela** [unknowntrojan/egui-d3d9#1]
Hello! I can add this change myself - but I'd rather remain upstream. What do you think about implementing an `EguiDx9` `ui_state` getter? Is this antithetical to the design, or something?

**Comment by unknowntrojan** [comment]
i don't follow. the menu callback has full access to the user-specified ui_state, as seen in the example. please elaborate. (im not opposed to this change, i just dont understand what it'd be for)

**Comment by cristeigabriela** [comment]
> i don't follow. the menu callback has full access to the user-specified ui_state, as seen in the example. please elaborate. (im not opposed to this change, i just dont understand what it'd be for)

I personally use the state to store if the menu is open or not, and I'd like to be able to read it outside of present/the callback.

**Comment by unknowntrojan** [comment]
thread-safety might be an issue, so we would need to wrap T in an rwlock.

also, this is how I usually handle menu opening and closing: https://i.imgur.com/EcroFkb.png

**Comment by cristeigabriela** [comment]
> thread-safety might be an issue, so we would need to wrap T in an rwlock.
> 
> also, this is how I usually handle menu opening and closing: https://i.imgur.com/EcroFkb.png

Yes I thought of that too, but I personally hold the UI in a context object which is already protected by RwLock. Couldn't this safely be offloaded to the user? Mutability could be handled by RefCell (valid if you want to use RwLock, as you can acquire write and modify your variable) and there'd be only an immutable borrow state getter function, because otherwise one can safely assume that interfering with the status is not safe.

**Comment by unknowntrojan** [comment]
Could you make a PR?

**Comment by cristeigabriela** [comment]
> Could you make a PR?

I went and thought about the idea again, implementing my desired behavior within the defined bounds, and I ended up with an `Arc<RefCell<MenuState>>`, then to access it I get a clone and borrow as I wish. I'm not sure if my idea makes sense anymore - so I'm sorry, I should've done this before opening an issue.

**Comment by unknowntrojan** [comment]
It's all fine. If you change your mind, simply re-open the issue.
