### ISSUE TITLE
Incorrect rendering of text and checkbox

### ISSUE THREAD

**Issue by pvolok** [unknowntrojan/egui-d3d9#14]
Thank you for this library. I am trying to use it to render overlay in Lineage 2.

There seem to be issues with rendering. I rendered the same app using egui-glow (winit window) and egui-d3d9.

Left: egui-glow
Right: egui-d3d9
![Untitled](https://github.com/unknowntrojan/egui-d3d9/assets/2015955/11b13318-6c17-4d87-86ed-86f9c541f4db)

Do you have any idea what might cause this problem?

**Comment by unknowntrojan** [comment]
I have encountered this issue as well, I have no idea what causes it. I have spent weeks trying to fix this to no avail, I'm afraid I have exhausted every idea I had.

**Comment by unknowntrojan** [comment]
That being said, if you do find the issue, please open a PR to get it merged. I will look at it again tonight, but I can't guarantee anything. DirectX is hard to debug.

**Comment by pvolok** [comment]
I tried to poke with the code without success. But I have zero experience with d3d/opengl.

**Comment by pvolok** [comment]
I think I found some clues. First, I tried to render 4 semi-transparent boxes. In the following picture you can see the difference in rendering. Left: d3d9. Right: egui-glow.

![image](https://github.com/unknowntrojan/egui-d3d9/assets/2015955/43ff8273-3273-4750-b2f2-c11dfb9a3d0d)

Looks like egui premultiplies colors and ignores alpha after. Then I changed `D3DRS_SRCBLEND` to `D3DBLEND_ONE`:

```rust
// before
// dev.SetRenderState(D3DRS_SRCBLEND, D3DBLEND_SRCALPHA.0 as _)?;

// after
dev.SetRenderState(D3DRS_SRCBLEND, D3DBLEND_ONE.0 as _)?;
```

And indeed it improved some things, but introduces another problem with text:

![image](https://github.com/unknowntrojan/egui-d3d9/assets/2015955/7f66a265-f6e3-4596-865f-04da78665f06)


I also noticed that other backends always include shaders, so maybe some work is done there. But I have no clue what those shaders are doing.

**Comment by pvolok** [comment]
With the above PR seems to be rendering identical.

![image_2023-10-05_14-05-56](https://github.com/unknowntrojan/egui-d3d9/assets/2015955/af531574-280e-44d0-abfa-ff6e88c25a1b)

**Comment by unknowntrojan** [comment]
Wow. I did tinker with the blending A LOT, and I mean **A LOT**, but I never really got it to work right (I spent WEEKS on this). Thank you so much for your contribution!
