### ISSUE TITLE
Input state seems broken

### ISSUE THREAD

**Issue by cestef** [unknowntrojan/egui-d3d9#6]
When getting 
```rust 
ui.input(|input| input.keys_down.clone());
```

The keys returned do not match with the ones pressed. I am using a QWERTZ keyboard (Swiss French layout). The "mapping" that is returned is the following:

```
Q => O
W => U
E => C
R => P
T => R
Z => X
```
Any similar known issues ? I can also provide more information on the problem if needed !

**Comment by cestef** [comment]
Also, "Control" keys, such as ArrowUp, Enter, Backspace, Space, Tab, etc. Work fine, only seems to be a problem with "Character" keys

**Comment by cestef** [comment]
I'm guessing it comes from the 3 first branches of the `match` in the `get_key` function from the input manager you are providing: https://github.com/unknowntrojan/egui-d3d9/blob/30ec8275e61b9790685570758d4d60eb1900ad41/egui-d3d9/src/inputman.rs#LL352-L376C2

**Comment by cestef** [comment]
Looking at https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes, the codes returned by `wparam` are correct, so it does not come from the matching after all, maybe it's just the `transmute`ing to egui's `Key` that is causing all of this.

**Comment by cestef** [comment]
if you look at https://docs.rs/egui/latest/egui/enum.Key.html, you can see that the enum's order does not match with the "Virtual Key Codes" one, there is an offset of 2 between both.
By removing 2 to each offset [here](https://github.com/unknowntrojan/egui-d3d9/blob/30ec8275e61b9790685570758d4d60eb1900ad41/egui-d3d9/src/inputman.rs#LL352-L376C2):
```rust
        0x30..=0x39 => unsafe { Some(std::mem::transmute::<_, Key>(wparam as u8 - 0x1F)) },
        0x41..=0x5A => unsafe { Some(std::mem::transmute::<_, Key>(wparam as u8 - 0x26)) },
        0x70..=0x83 => unsafe { Some(std::mem::transmute::<_, Key>(wparam as u8 - 0x3B)) },
```
I am now getting the correct keys, I don't know what this is due to, and it may be a little bit hacky, but I guess it works for me x)

**Comment by unknowntrojan** [comment]
sorry for the late reply, good catch. will merge.

**Comment by unknowntrojan** [comment]
if you want, you can submit a patch to https://github.com/sy1ntexx/egui-d3d11 and https://github.com/mfloob/egui-opengl-internal which share the same input manager code.
