### ISSUE TITLE
broken build

### ISSUE THREAD

**Issue by ghost** [unknowntrojan/egui-d3d9#8]
cargo build
warning: associated function `from_raw` is never used
  --> egui-opengl-internal\src\painter.rs:61:12
   |
61 |     pub fn from_raw(id: u32) -> Self {
   |            ^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: associated function `new_opengl_texture` is never used
   --> egui-opengl-internal\src\painter.rs:212:12
    |
212 |     pub fn new_opengl_texture(&mut self, openl_id: u32) -> egui::TextureId {
    |            ^^^^^^^^^^^^^^^^^^

warning: associated function `new_user_texture` is never used
   --> egui-opengl-internal\src\painter.rs:220:12
    |
220 |     pub fn new_user_texture(
    |            ^^^^^^^^^^^^^^^^

warning: associated function `update_user_texture_data` is never used
   --> egui-opengl-internal\src\painter.rs:245:12
    |
245 |     pub fn update_user_texture_data(&mut self, texture_id: &egui::TextureId, pixels: &[Color32]) {
    |            ^^^^^^^^^^^^^^^^^^^^^^^^

warning: `egui-opengl-internal` (lib) generated 4 warnings
   Compiling retour v0.1.0
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> C:\Users\icetrix\.cargo\registry\src\github.com-1ecc6299db9ec823\retour-0.1.0\src\lib.rs:4:3
  |
4 |   feature(unboxed_closures, abi_thiscall, tuple_trait)
  |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> C:\Users\icetrix\.cargo\registry\src\github.com-1ecc6299db9ec823\retour-0.1.0\src\lib.rs:4:43
  |
4 |   feature(unboxed_closures, abi_thiscall, tuple_trait)
  |                                           ^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `retour` due to 2 previous errors
PS C:\Users\icetrix\egui-opengl-internal> 

what do?

**Comment by unknowntrojan** [comment]
sorry, I should have documented this better. This crate only works on nightly versions of rust. https://rust-lang.github.io/rustup/concepts/channels.html

**Comment by unknowntrojan** [comment]
I have investigated and found that it is an unnecessary requirement. I have updated the crate to no longer require nightly. Have fun!
