### ISSUE TITLE
compile failed

### ISSUE THREAD

**Issue by ghost** [unknowntrojan/egui-d3d9#9]
how to fix?

![image](https://user-images.githubusercontent.com/120610440/232305944-6db82a3b-502c-4aa9-bd7a-2dbb2ceffe45.png)

**Comment by unknowntrojan** [comment]
use the nightly version of rust ([rustup](https://rust-lang.github.io/rustup/concepts/channels.html)).

I'll take another look later to see if I can make it work on the stable channel, but if I'm gonna be honest, the stable channel is a meme. The features on nightly are "stable", just not "stabilized" by the rust developers.
